// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2084.robotsimulator.commands;

import org.usfirst.frc2084.robotsimulator.RobotViewer;
import org.usfirst.frc2084.robotsimulator.wpilibj.SmartDashboard;
import org.usfirst.frc2084.robotsimulator.wpilibj.command.Command;

/**
 *
 */
public class TeleopBackground extends Command {
    private RobotViewer robotViewer;
    

    public TeleopBackground() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        robotViewer = new RobotViewer();
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//        if (Robot.oi.getLeftJoystick().getZ() > 0) {
//            Robot.climbingSubsystem.climbingModeEnabled = true;
//        } else {
//            Robot.climbingSubsystem.climbingModeEnabled = false;
//        }
        SmartDashboard.putData(robotViewer);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
