// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2084.CMonster.subsystems;
import com.sun.squawk.util.MathUtils;
import org.usfirst.frc2084.CMonster.RobotMap;
import org.usfirst.frc2084.CMonster.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveBaseSubsystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    AnalogChannel ultrasonicInput = RobotMap.driveBaseSubsystemUltrasonicInput;
    SpeedController rightJaguar = RobotMap.driveBaseSubsystemRightJaguar;
    SpeedController leftJaguar = RobotMap.driveBaseSubsystemLeftJaguar;
    RobotDrive robotDrive = RobotMap.driveBaseSubsystemRobotDrive;
    Gyro f;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new TeleopDriveCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    public int getUltrasonicDistance() {
        return (int)MathUtils.round(ultrasonicInput.getVoltage() / 0.00977);
    }
}
